version: "3.3"

services:
    mariadb:
        image: mariadb
        volumes:
            - db_data:/var/lib/mysql
        restart: on-failure
        env_file:
            - .env

    wordpress:
        build: ./requirements/wordpress/
        volumes:
            - ./requirements/wordpress/php/:/var/www/html
        depends_on:
            - mariadb
        links:
            - mariadb
        restart: on-failure
        env_file:
            - .env

    nginx:
        build: ./requirements/nginx/
        volumes:
            - /data/html:/var/www/html
        ports:
            - "443:443"
        links:
            - wordpress
volumes:
    db_data: {}
