version: "3.3"

services:
    mariadb:
        image: mariadb:final
        build: 
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        volumes:
            - db_volume:/var/lib/mysql
        restart: always
        networks:
            - back
        env_file:
            - .env

    wordpress:
        image: wordpress:final
        build:
            context: ./requirements/wordpress/
            dockerfile: Dockerfile
        #container_name: wordpress
        volumes:
            - wp_volume:/var/www/html
        depends_on:
            - mariadb
        networks:
            - front
            - back
        restart: always
        env_file:
            - .env

    nginx:
        image: nginx:final
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        volumes:
            - wp_volume:/var/www/html
        ports:
            - "443:443"
        networks:
            - front
        restart: always

networks:
        front:
        back:

volumes:
    wp_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/robriard/data/wp'
    db_volume:
            driver: local
            driver_opts:
                type: 'none'
                o: 'bind'
                device: '/home/robriard/data/db'
