version: "3.3"

services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        volumes:
            - db_volume:/var/lib/mysql
        restart: always
        tty: true
        stdin_open: true
        networks:
            - back
        env_file:
            - .env

    wordpress:
        build: ./requirements/wordpress/
        container_name: wordpress
        volumes:
            - wp_volume:/var/www/html
        depends_on:
            - mariadb
        networks:
            - front
            - back
        restart: always
        env_file:
            - .env

    nginx:
        build: ./requirements/nginx/
        container_name: nginx
        volumes:
            - wp_volume:/var/www/html
        ports:
            - "443:443"
        networks:
            - front
        restart: always

networks:
        front:
        back:

volumes:
    wp_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/robriard/data/wp'
    db_volume:
            driver: local
            driver_opts:
                type: 'none'
                o: 'bind'
                device: '/home/robriard/data/db'
